package com.suncode.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserlog<M extends BaseUserlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setLoginip(java.lang.String loginip) {
		set("loginip", loginip);
		return (M)this;
	}
	
	public java.lang.String getLoginip() {
		return getStr("loginip");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	/**
	 * type:1登录 2：退出
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * type:1登录 2：退出
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setOpcontent(java.lang.String opcontent) {
		set("opcontent", opcontent);
		return (M)this;
	}
	
	public java.lang.String getOpcontent() {
		return getStr("opcontent");
	}

}
