package com.suncode.common.model.bean;

import com.suncode.common.model.base.BaseToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Token extends BaseToken<Token> {
    public static Token dao = new Token();
}
