package com.suncode.common.model.bean;

import com.suncode.common.model.base.BaseUserlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userlog extends BaseUserlog<Userlog> {

}
